### ISSUE TITLE
Strange layout due to ghost "R" in guides page

### ISSUE THREAD

**Issue by AliSoftware** [CocoaPods/guides.cocoapods.org#113]
In the [Root Specification Guides page](https://guides.cocoapods.org/syntax/podspec.html#group_root_specification) there is some white "R" next to some section titles in the left bar.

Don't know where it comes from, but this "R" disturbs the menu layout
<img width="280" alt="ghost white R in Guides menu" src="https://cloud.githubusercontent.com/assets/216089/14989968/cb0dd396-115a-11e6-8473-1f58148538e9.png">

```html
<li>
  <a class="select-tab" data-toggle="tab" href="#tab_name">name</a>
  <span class="label label-small">R</span>
</li>
<li>
  <a class="select-tab" data-toggle="tab" href="#tab_version">version</a>
  <span class="label label-small">R</span>
</li>
```

**Comment by orta** [comment]
Aye, looks like its something that all the required properties had

**Comment by AliSoftware** [comment]
That was fast! Not sure to get how your fix solves it but HTML and CSS are all magic to me anyway ^^
