### ISSUE TITLE
scoreme.report link broken

### ISSUE THREAD

**Issue by fulldecent** [CocoaPods/guides.cocoapods.org#128]
On https://guides.cocoapods.org/making/quality-indexes.html

There is a link to http://scoreme.report/ which is currently broken.

Please advise if there is an alternate way for developers to test their readme file against the algorithm.

**Comment by orta** [comment]
Looks like it moved back to a github page instead: https://github.com/clayallsopp/readme-score/commit/42b6a57b6bae10017dd6903aab6fba6ae2f5537e
