### ISSUE TITLE
"Using CocoaPods" does not show how to handle typical test targets

### ISSUE THREAD

**Issue by dusek** [CocoaPods/guides.cocoapods.org#130]
Typical app project created by Xcode nowadays has 3 targets:

1. the main, app target
2. unit tests target
3. UI tests target

Unfortunately after reading "Using CocoaPods", I still have no idea how to deal with the tests target, namely:

- should I make the test targets depend on the same pods as the main app target?
- how should I structure my `Podfile`?

**Comment by k0nserv** [comment]
Hey, could you please post this questions on Stackoverflow instead as we like to keep the issues free from usage questions. 

On the topic of the guides they can definitely stand to be improved so if you could raise an issue with the points you think are unclear and we can improve the guides to make those points clearer.
