### ISSUE TITLE
Version 1.0.1 requires an update to Ruby

### ISSUE THREAD

**Issue by pdshelley** [CocoaPods/guides.cocoapods.org#133]
The latest version of CocoaPods requires a newer version of Ruby (I believe 2.2.2) then what OS X ships with (I believe 2.0.0).  The last question in the F.A.Q “Why do I have to install Ruby to use CocoaPods?” needs to be updated or there is an dependency on a newer version of Ruby by mistake. 

https://guides.cocoapods.org/using/faq.html

**Comment by segiddins** [comment]
This is fixed in the 1.1 betas
