### ISSUE TITLE
Getting 'TypeError - no implicit conversion of Array into String'

### ISSUE THREAD

**Issue by pavm035** [CocoaPods/guides.cocoapods.org#141]
Hi,

/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]
    RubyGems : 2.4.5.1
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /usr/local/Cellar/ruby/2.2.3/lib
Repositories :*********
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-keys        : 1.6.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile


abstract_target 'available_pods' do
pods..........
    
    # Targets
    target 'mainApp' do
        pod 'Reveal-iOS-SDK', :configurations => ['Debug','Enterprise','Calabash'], :inhibit_warnings => true
        target 'Atlas'        
    end
end

target 'UnitTests' do
   pod 'tuneup_js', '~> 0.0.1'
  pod 'OCMock', '3.1.1'
end

When we use :configurations => ['Debug','Enterprise','Calabash'], :inhibit_warnings =>  inside nested target it throws that error, I could not find solution so far, Thanks in advance.

**Comment by segiddins** [comment]
Please share your entire Podfile and the backtrace of the error in an issue on https://github.com/CocoaPods/CocoaPods, thanks!

**Comment by pavm035** [comment]
@segiddins  Thanks for the update, but i found similar issue already here, it would be great help to resolve there https://github.com/CocoaPods/CocoaPods/issues/5366
