### ISSUE TITLE
Dead link to "wiki on cross dependency resolution" in Specs and the Specs Repo

### ISSUE THREAD

**Issue by timbroder** [CocoaPods/guides.cocoapods.org#147]
The link to *wiki on cross dependency resolution* in [section 2](https://github.com/CocoaPods/guides.cocoapods.org/blob/7ca3d89b3dfb50e385a3dac5ef4dfee6fc12d0d2/source/making/specs-and-specs-repo.html.md#how-does-the-specs-repo-work "section 2") of *Specs and the Specs Repo* is a dead link.

I can submit a PR to remove it or point to a new location if you can point me to where it is. I did some googling myself but couldn't find it

**Comment by Justin0123** [comment]
https://en.wikipedia.org/wiki/Circular_dependency , this maybe can help you.
