### ISSUE TITLE
Site seems down

### ISSUE THREAD

**Issue by LoganWright** [CocoaPods/guides.cocoapods.org#149]
Visiting https://guides.cocoapods.org/ returns the following page for me:

<img width="949" alt="screen shot 2017-02-23 at 11 00 48 pm" src="https://cloud.githubusercontent.com/assets/5750489/23281078/07116182-fa1c-11e6-9bcc-b2780042b36f.png">

Not sure if it's just me 👍 

browser: Chrome
com: mbp

(I'm also not in US if that might matter for some reason)

**Comment by DanToml** [comment]
Huh weird, seems to be working for me tunneled through Germany from the UK :thinking:. That error doesn't make sense if you're using guides.ccoapods.org directly either :confused:

**Comment by orta** [comment]
Likely was due to https://www.theregister.co.uk/2017/02/24/cloudbleed_buffer_overflow_bug_spaffs_personal_data/

**Comment by LoganWright** [comment]
Not sure what was going on here, possibly a remnant of cloud bleed like @orta suggested. Either way, it's working now for me, so I'll close this. Thanks 👍
