### ISSUE TITLE
Example of podfile 'source' syntax using incorrect formatting

### ISSUE THREAD

**Issue by commscheck** [CocoaPods/guides.cocoapods.org#150]
At the following link: https://guides.cocoapods.org/syntax/podfile.html#source

The text "Specifying to first use the Artsy repository and then the CocoaPods Master Repository" should be on one line, but half of the line is captured by the code block formatting.

According to the [CONTRIBUTING](https://github.com/CocoaPods/guides.cocoapods.org/blob/master/CONTRIBUTING.md) file for this repo, this page is auto generated from the docs in the [dsl.rb](https://github.com/CocoaPods/Core/blob/master/lib/cocoapods-core/podfile/dsl.rb) file in Core.

Apologies, I'm not familiar with how this auto generation works. I'm not sure if this is an issue with the doc formatting in the ruby file, or if it's an issue with the docs generation incorrectly interpreting the formatting.

**Comment by orta** [comment]
Thanks for the issue!

Looks like it probably needs to be moved to a single liner in the DSL, with perhaps a rubocop disable line length added. Either that or it could be re-worded to fit one line.
