### ISSUE TITLE
Should the Manifest.lock file be added to git or not?

### ISSUE THREAD

**Issue by revolter** [CocoaPods/guides.cocoapods.org#159]
Either the response, it should be added to the docs, as it (`Manifest.lock`) is currently [not mentioned](https://www.google.com/search?q=site%3Aguides.cocoapods.org+manifest.lock) at all.

**Comment by orta** [comment]
always

**Comment by revolter** [comment]
I am 100% I saw a mention somewhere that it shouldn't be, as it's always equal to `Podfile.lock` and because it's only used for an internal check or something.

Also, wow that was fast 😲.

**Comment by orta** [comment]
Oh, manifest, nah - it's part of the Pods folder - IMO it doesn't need to be in the guides

**Comment by orta** [comment]
It's covered in this: https://guides.cocoapods.org/using/using-cocoapods.html#should-i-check-the-pods-directory-into-source-control

**Comment by revolter** [comment]
Ok

**Comment by Jon889** [comment]
There is no mention of the Manifest.lock in that guide?

**Comment by orta** [comment]
Ah, sounds like an oversight - I'd recommend adding it 👍

**Comment by Jon889** [comment]
So the guidance is that if you have the Pods directory added to git, then the Manifest.lock shouldn’t be or doesn’t need to be added?

**Comment by orta** [comment]
Regardless of whether you put Pods in, you should have `Manifest.lock` in git 👍
