### ISSUE TITLE
Google Map,Place, Picker Pod not installing 

### ISSUE THREAD

**Issue by abhishekraics001** [CocoaPods/guides.cocoapods.org#165]
My Pod 
1.=====================================================
source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
target 'Hospi24Cares' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hospi24Cares
pod 'Alamofire', '~> 4.4'
pod 'AlamofireImage', '~> 3.3'
pod 'SwiftyJSON', '~> 4.0'
pod 'SDWebImage', '~> 4.0'
pod 'SDWebImage/WebP'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'IQKeyboardManager', '~> 6.1'
pod 'GooglePlaces'

end

2.===========going to project path==========================================
pod install

3.======================================================
[!] Error installing GoogleMaps
[!] /usr/bin/curl -f -L -o /var/folders/3s/rxd_gd250gld057xqq6tlktr0000gn/T/d20180926-34798-aggcqm/file.tgz https://dl.google.com/dl/cpdc/f4086b0aa122de6c/GoogleMaps-2.7.0.tar.gz --create-dirs --netrc-optional

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to dl.google.com:443 

Please help me on Priority

**Comment by dnkoutso** [comment]
This is the wrong project to file this issue. Furthermore this looks like a network configuration issue and you cannot reach `dl.google.com`. Please inspect your network configuration.

**Comment by abhishekraics001** [comment]
Pls help me how can i resolved this issue.
i totally tired with hit & try process:)
