### ISSUE TITLE
Google Map, Place, Picker

### ISSUE THREAD

**Issue by abhishekraics001** [CocoaPods/guides.cocoapods.org#166]
/*******************************************************/
1. My Pod file 

source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
target 'Hospi24Cares' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hospi24Cares
pod 'Alamofire', '~> 4.4'
pod 'AlamofireImage', '~> 3.3'
pod 'SwiftyJSON', '~> 4.0'
pod 'SDWebImage', '~> 4.0'
pod 'SDWebImage/WebP'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'IQKeyboardManager', '~> 6.1'
pod 'GooglePlaces'
end

2. /***********************************************************/
When i try to install pod file gating below Error  like :-  pod install with directory path
Luminouss-MacBook-Pro:AKSwiftSlideMenu-master 2 luminous$ pod install
Analyzing dependencies
Downloading dependencies
Using Alamofire (4.7.3)
Using AlamofireImage (3.3.1)
Installing GoogleMaps (2.7.0)

[!] Error installing GoogleMaps
[!] /usr/bin/curl -f -L -o /var/folders/3s/rxd_gd250gld057xqq6tlktr0000gn/T/d20180926-42159-acvjtk/file.tgz https://dl.google.com/dl/cpdc/f4086b0aa122de6c/GoogleMaps-2.7.0.tar.gz --create-dirs --netrc-optional

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to dl.google.com:443 

Luminouss-MacBook-Pro:AKSwiftSlideMenu-master 2 luminous$ 

*** Please help if possible on priority

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
