### ISSUE TITLE
请问如何遍历project或者遍历workspace的target

### ISSUE THREAD

**Issue by biostome** [CocoaPods/guides.cocoapods.org#176]
How to traverse the project or traverse the target of the workspace?
I have a lot of targets

**Comment by amorde** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

With that said, using Xcodeproj you can do something like this:


```
# Podfile

post_install do |context|
    context.pods_project.targets.each do |target|
        # Do something with `target` here
    end
end
```
