### ISSUE TITLE
Pointing to unknown document

### ISSUE THREAD

**Issue by Skippern** [CocoaPods/guides.cocoapods.org#20]
When executing pod install I am pointed to an unknown document (issue on this site):

bash-3.2$ pod install MapBox     
WARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
See https://github.com/CocoaPods/guides.cocoapods.org/issues/26 for
possible solutions.

As can see, there are only 19 issues created, this what I am writing now probably will be issue 20, so how can I find a solution to the problem?

I get the following error message when executing install:
### Stack

```
   CocoaPods : 0.33.1
        Ruby : ruby 2.0.0p451 (2014-02-24 revision 45167) [universal.x86_64-darwin13]
    RubyGems : 2.0.14
        Host : Mac OS X 10.9.4 (13E28)
       Xcode : 5.1.1 (5B1008)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ ace937d3ef44e3c8da9274e7f908b6f30ef3e93e
```

### Error

```
NoMethodError - undefined method `ansi' for nil:NilClass
/Library/Ruby/Gems/2.0.0/gems/claide-0.6.1/lib/claide/command/validation_helper.rb:77:in `prettify_validation_suggestion'
/Library/Ruby/Gems/2.0.0/gems/claide-0.6.1/lib/claide/command/validation_helper.rb:21:in `argument_suggestion'
/Library/Ruby/Gems/2.0.0/gems/claide-0.6.1/lib/claide/command.rb:436:in `validate!'
/Library/Ruby/Gems/2.0.0/gems/claide-0.6.1/lib/claide/command.rb:280:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/bin/pod:33:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```
[!] Oh no, an error occurred.

Search for existing github issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60ansi%27+for+nil%3ANilClass&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Don't forget to anonymize any private data!

--------

Probably should report this issue on CocoaPods, but I am pointed here as well.

**Comment by orta** [comment]
I think this is fixed in later CP releases.
