### ISSUE TITLE
Refactor documentation for private pods

### ISSUE THREAD

**Issue by kylef** [CocoaPods/guides.cocoapods.org#28]
http://guides.cocoapods.org/making/private-cocoapods.html

Some things are no longer relevant:

> If you plan on forking a library that is already part of the Master Spec repo, for now we suggest choosing a name that starts with a letter before M (due to spec repos loading in alphabetical order, see #982).

"The Podfile" should show sources in all example, showing master and private in some cases:

http://guides.cocoapods.org/using/the-podfile.html

**Comment by AliSoftware** [comment]
Is this still relevant since #70 has been merged? \cc @orta @mattmorton

**Comment by orta** [comment]
I think this is fixed now we're including examples.
