### ISSUE TITLE
Podspec Syntax Reference should document the JSON podspec format

### ISSUE THREAD

**Issue by irace** [CocoaPods/guides.cocoapods.org#48]
The [Podspec Syntax Reference](http://guides.cocoapods.org/syntax/podspec.html) should be updated to also document the JSON format. This would make it significantly easier to build tooling on top of the JSON specifications. 

For example, in Ruby there are [three different ways](http://guides.cocoapods.org/syntax/podspec.html#authors) to populate the `authors` field. It'd be great to document if these three different ways are *also* valid in JSON.

**Comment by colinbrash** [comment]
This continues to be an issue over a year later, and it may have effects the Cocoapods dev team has not foreseen.

One of our clients has an internal podspec repo and we are spending much too much thought on whether we should allow JSON specs or not.  No one truly understand what the ramifications are of one vs. the other.  The only thing we have to go on right now for JSON format reference is that blog post, plus the examples in the repo.

We don't understand:
* Are there limitations to one or the other?
* Is one the preferred format?
* What *is* the format?  (For the most part it does seem to line up with the Ruby format, but where are the differences?)
* What is the intended future of podspecs?  (Support both formats indefinitely?  Phase one out someday?)

> As far as it goes I'm not seeing a particular demand for this outside of just @irace at the minute too.

This is a self fulfilling prophecy.  If you do not document the JSON format and discuss it, demand will of course be extremely low.  Even if they learn about it somehow, no one wants to adopt something that has zero public support.

**Comment by orta** [comment]
This post feels a little bit confrontational for bringing up a thread from 2014. Please be more respectful. 

The CocoaPods [Specs](https://github.com/cocoapods/specs) repo is, and always will be JSON. So it's always going to be supported in CocoaPods. We do that so that you don't have to have arbitrary code running on your computer.

> Are there limitations to one or the other?

Ruby Podspec are turing-complete, JSON specs are not. They both can turn in the same model objects in CocoaPods though.

> Is one the preferred format? What is the format? (For the most part it does seem to line up with the Ruby format, but where are the differences?)

Yes, Ruby.

What is the intended future of podspecs? (Support both formats indefinitely? Phase one out someday?)

The same as it has been, you should be making Ruby podspecs, as this thread shows, if you care enough you can make JSON podspecs but you're going against the grain.

**Comment by orta** [comment]
Which brings me to another point I guess, I said I wasn't planning on doing it back in 2014, I'm not definitely not going to build it into the guides in 2016, so this issue can probably be closed. 

If someone makes a PR adding it all, I'm game for discussing it there, but I'm not planning on adding support.

**Comment by irace** [comment]
Agree with @orta, please keep discourse civil.

> The same as it has been, you should be making Ruby podspecs, as this thread shows, if you care enough you can make JSON podspecs but you're going against the grain.

If this is the case due to lack of resources on the CocoaPods team to fully document the JSON pod spec file, audit all the places in which the CocoaPods CLI tools assume Ruby, etc., I 100% understand.

If this is an explicit design decision, I'd love more context around why.

**Comment by orta** [comment]
Nah, not an explicit design decision, Ruby offers more dev freedom and easily is transformed into the other.

**Comment by irace** [comment]
Thanks.!

I’d like to think that, all things being equal, JSON would be the preferred format while Ruby would still be there for power users.

But all things aren’t equal and considering I’m not spending my own time making this so, no complaints from me :+1: :+1:

**Comment by orta** [comment]
hah - but yeah, I know where your coming from.

**Comment by colinbrash** [comment]
Apologies if my post sounded confrontational or uncivil.  That certainly was not the intention.
And thanks for taking the time to clarify, this is helpful for our team.
