### ISSUE TITLE
Add more detail to 'Podfile syntax reference: Xcodeproj'

### ISSUE THREAD

**Issue by Ashton-W** [CocoaPods/guides.cocoapods.org#54]
http://guides.cocoapods.org/syntax/podfile.html#xcodeproj

From the Podfile reference I'm not understanding why or when I would use `xcodeproj` to specify a build configuration.

Do I always need to do this if I use configurations other than the Xcode defaults of 'Debug' and 'Release'?
What does this do?

**Comment by AliSoftware** [comment]
Good point.

The answer is that you may only omit the `xcodeproj` attribute in your Podfile:

* if you don't need to specify special configurations other than `Debug` and `Release`…
* and if you only have one `.xcodeproj` project file that lies next to your Podfile, so that CocoaPods can infer it and choose this project for the pods integration.

If you have multiple `.xcodeproj` files next to your Podfile, or that your `.xcodeproj` is in another folder (like in a subfolder), then you need to specify that so that CocoaPods can know which `.xcodeproj` to use.


All this indeed needs to be specified in the guide (Feel free to make a PR).

**Comment by Ashton-W** [comment]
Thanks @AliSoftware.

Could you elaborate on configurations? For example, I often duplicate the Release configuration to create a Beta one. I haven't ran into any problems.

Do some pods integrate differently in Debug and Release?

**Comment by AliSoftware** [comment]
AFAIK, Specifying the configurations as in `xcodeproj 'TestProject', 'Beta' => :release` allows CocoaPods to setup this configuration in your App's xcodeproj to use the `Pods.xcconfig` files (defining the correct Build Settings for `HEADER_SEARCH_PATH` and frameworks to link etc).

If you don't specify the `'Beta' => :release` part, your targets' configurations Build Settings will not be configured to inherit from the `Pods-*.xcconfig` files (see capture below), thus won't be ensured to link with the appropriate frameworks or be configured to find the pod headers etc.

![baseconfigs](https://cloud.githubusercontent.com/assets/216089/5842666/e88be89c-a1a6-11e4-8717-580fe49f057d.png)

**Comment by AliSoftware** [comment]
And to complete my answer:  there is generally no difference between Debug & Release in the common case where you simply list pods in your `Podfile`, but know that you can activate some pods only on given configurations. See [the 'pod' page in the Guides](http://guides.cocoapods.org/syntax/podfile.html#pod) (especially paragraph about "Build Configurations").

For example one may only use some pods during Debug but not when publishing in the AppStore nor making a Release build:
```
pod 'MyAwesomeDebuggingKit', :configuration => ['Debug']
```

**Comment by Ashton-W** [comment]
Wow thanks for the detailed responses.

What is the default `xcodeproj` configuration (`:debug`, `:release`) for additional configurations like my 'Beta' example?

**Comment by AliSoftware** [comment]
The default is the same as Xcode default configuration names, namely "Debug" and "Release", so those two are equivalent:

```
xcodeproj 'path/to/myProject'
# is equivalent to 
xcodeproj 'path/to/myProject', 'Debug' => :debug, 'Release' => :release
```

But IIRC, specifying an additional  configuration on the `xcoddproj` line simply *add* additional configurations to which you want your pods to be integrated, still keeping the default 'Debug' and 'Release' configurations. So you don't have to repeat them when you specify configurations in the `xcodeproj` line, you can simply add `'Beta' => :release` and pods will be integrated with Debug, Release and Beta.

**Comment by Ashton-W** [comment]
Cocoapods already integrates with the 'Beta' configuration without me specifying anything. My generated `xcconfig`s are identical so I can't tell the difference. I'll do some playing around - do you happen to know a pod that has different `:Debug` behaviour?

**Comment by AliSoftware** [comment]
If you already did the CocoaPods integration once (already ran `pod install` on your project when you once had `xcodeproj 'Foo', 'Beta' => :release` in your `Podfile` once) then it's normal that the Beta configuration is already integrated (The integration — namely adding reference to the Pods project & linking the project with `libPods.a` and adding the `xcconfig` files — is only done the first time you integrate pods to your project)

**Comment by AliSoftware** [comment]
About difference between telling if a configuration behaves like `:debug` or like `:release`, I actually don't have any pod in mind that may behave differently, but another difference between those two configurations is in the Build Settings of the Pods targets itself, especially for stuff like `Build Active Architectures only` and such.

The "Pods" project does only have "Debug" and "Release" configuration. If you compile your workspace in Debug configuration, both your App and the Pods project will be compiled using the "Debug" configuration. But if you add a 'Beta' configuration in your App project, as the Pods project does not have a matching configuration, we have to know if we should build the Pods project with its Debug or Release configuration when you build the App with its Beta configuration

**Comment by amorde** [comment]
Closing as this appears to be handled by http://guides.cocoapods.org/syntax/podfile.html#project
