### ISSUE TITLE
Please add the need to run 'pod setup' to install guide

### ISSUE THREAD

**Issue by rhtx** [CocoaPods/guides.cocoapods.org#59]
See Kim's answer : http://stackoverflow.com/questions/27053344/cocoapods-install-error

This has tripped me up twice, and I've spent a couple of hours finding/re-finding the solution (bad on me for having to re-find).  Thanks!

**Comment by orta** [comment]
We're planning a release extremely soon which should fix this bug.

**Comment by rhtx** [comment]
Awesome.  Thanks for the extraordinarily quick response.
