### ISSUE TITLE
Broken link in breadcrumb

### ISSUE THREAD

**Issue by jamonholmgren** [CocoaPods/guides.cocoapods.org#60]
![broken link](http://clrsight.co/jh/2015-02-25-f0635.png?+)

Would submit a PR but don't quite have time to track this down. Just FYI.

**Comment by orta** [comment]
thanks :)

**Comment by dkhamsing** [comment]
Maybe related but these top links in the footer are broken

![screen shot 2015-03-05 at 11 08 48 am](https://cloud.githubusercontent.com/assets/4723115/6512349/2f9c0fe4-c328-11e4-9282-f2573c219127.png)

1. http://guides.cocoapods.org/using/index.html
- http://guides.cocoapods.org/making/index.html
- http://guides.cocoapods.org/contributing/index.html

**Comment by orta** [comment]
All of these used to work, wonder what changed.
