### ISSUE TITLE
Making a CocoaPod: adding tags

### ISSUE THREAD

**Issue by kimjune01** [CocoaPods/guides.cocoapods.org#62]
http://guides.cocoapods.org/making/making-a-cocoapod.html

As a newbie using this guide, I had no idea that I was supposed to:
git tag '0.1.0'
git push --tag

Because a guide is supposed to help new users, I really think those two should be included with a brief description.

**Comment by orta** [comment]
This is in the [Release Section](http://guides.cocoapods.org/making/making-a-cocoapod.html#release)

```
$ pod lib lint

$ git add -A && git commit -m "Release 0.0.1."
$ git tag '0.0.1'
$ git push --tags
```
