### ISSUE TITLE
Bundle'd plugins aren't included in the command line guide

### ISSUE THREAD

**Issue by orta** [CocoaPods/guides.cocoapods.org#64]

**Comment by alloy** [comment]
Do you mean plugins in your Gemfile? If so, are you using `bundle exec pod --help`? I’m pretty sure they used to show up and that’s what I would expect.

**Comment by kylef** [comment]
@alloy I think @orta is referring to 'trunk', 'try' (the plugins bundled with CocoaPods) are not shown in the command line guides.

Isn't trunk shown here: http://guides.cocoapods.org/terminal/commands.html#group_trunk ?

**Comment by alloy** [comment]
Owww, yeah that would make sense, seeing which repo this is on :smile:

**Comment by segiddins** [comment]
So which plugins should be included on the guides?

**Comment by orta** [comment]
As kyle pointed out, we've got this for trunk, so just `try`, basically

**Comment by AliSoftware** [comment]
Maybe add `plugins` too then?

**Comment by orta** [comment]
yes

**Comment by segiddins** [comment]
Closed via https://github.com/CocoaPods/guides.cocoapods.org/commit/4ede1acbd0b9bbd21d8c7447fb960b802f10deb2.
