### ISSUE TITLE
More explanation of differences between podspec's xcconfig and compiler_flags

### ISSUE THREAD

**Issue by mtitolo** [CocoaPods/guides.cocoapods.org#65]
Aka `xcconfig` is for final integration, `compiler_flags` for pod compilation only

Goes well with #63

**Comment by orta** [comment]
This fixes the issue - https://github.com/CocoaPods/CocoaPods/pull/3573

**Comment by orta** [comment]
Closing as 0.38 makes the DSL much clearer
