### ISSUE TITLE
Create a page about the quality indicators

### ISSUE THREAD

**Issue by orta** [CocoaPods/guides.cocoapods.org#77]
Go through the one's that exist and talk about how they work.

**Comment by beriberikix** [comment]
Thanks Orta! Any progress here? We'd love to follow best-practices here to raise the quality of our Pods. In lieu of a guide, is there an ideal Pod we can model after?

**Comment by kylef** [comment]
There isn't a guide yet, but you can look at the quality page for one of your Pods (https://cocoapods.org/pods/Hyperdrive/quality). You can click on the "Show metrics not applied" to view things not applied, should give you an indication of where things can be improved.

**Comment by beriberikix** [comment]
Thanks Kyle, very helpful. Can you confirm how the [README score](https://github.com/CocoaPods/cocoadocs-api/blob/master/quality_modifiers.rb#L65) is calculated? Is it via [clayallsopp/readme-score](https://github.com/clayallsopp/readme-score)?

**Comment by kylef** [comment]
@beriberikix Yes that's right.

**Comment by beriberikix** [comment]
:+1:

**Comment by beriberikix** [comment]
One more thing! How is the documentation score generated? What if we choose to use documentation_url and point to our doc page?

**Comment by orta** [comment]
The Documentation score comes from how much of your public, API ( e.g. header files ) is documented using either headerdoc or swiftdoc style formatting. I'll devote some time to a guide today.

**Comment by orta** [comment]
Done: https://guides.cocoapods.org/making/quality-indexes

**Comment by beriberikix** [comment]
w00t, you guys rock! :metal: :guitar: :microphone: :metal:
