### ISSUE TITLE
Quality Indexes typos

### ISSUE THREAD

**Issue by abbeycode** [CocoaPods/guides.cocoapods.org#82]
I went to clone the guides repo to fix some typos on the [Quality Indexes page](https://guides.cocoapods.org/making/quality-indexes), so I clicked on the [Pull Request link](https://github.com/CocoaPods/guides.cocoapods.org/blob/master/source/making/quality-indexes.html.md) on the bottom of the page, which took me to a MarkDown file that has 8 lines - this can't be the same page, can it?

**Comment by orta** [comment]
The page is generated from https://github.com/CocoaPods/cocoadocs-api/blob/master/quality_modifiers.rb

I've made a note in the page when you hit the pull request button: https://github.com/CocoaPods/guides.cocoapods.org/commit/bd59935d8e7fd0e94abde56d9937e833fb3276e6
