### ISSUE TITLE
Git version requirements for Podspec dependencies

### ISSUE THREAD

**Issue by FredericJacobs** [CocoaPods/guides.cocoapods.org#92]
>  [!] Invalid `X.podspec` file: [!] Unsupported version requirements. Updating CocoaPods might fix the issue.

It looks like dependencies, unlike Pods, can't be specified by a self-assigned git tag or commit. Is there a specific reason for that?

Something like:

```
s.dependency 'PodName', :git => 'https://github.com/X/Y.git', :commit => '94b7cf5b59a5c99cd5ca3957d4fa2435953d3f44'
```

Thanks!

**Comment by kylef** [comment]
Yes, see @alloy's comment on http://stackoverflow.com/a/22475228/221706.

**Comment by FredericJacobs** [comment]
Makes sense, thanks @kylef.

**Comment by FredericJacobs** [comment]
@kylef : Do you know a way of using a local podspec dependency (for development) without having to constantly push changes of that dependency to the CocoaPods directory?

**Comment by alloy** [comment]
@FredericJacobs Not sure I fully follow, but do you maybe mean the local path option? (https://guides.cocoapods.org/syntax/podfile.html#pod)

Any pod that you specify in your Podfile (with source options such as `:path`) will override the same pod being used down in the dependency graph.

**Comment by FredericJacobs** [comment]
@alloy : Thanks, that helps!

**Comment by alloy** [comment]
@FredericJacobs Perfect, np :+1:
